[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_2024 = "GomdUV61LpZJdX9m2mVEVrbX1GNhwRZDKcuBRG1xVxUe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
